repos:
  - repo: builtin
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: detect-private-key

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.15.22
    hooks:
      - id: ruff
        args: [ --config, pyproject.toml, --fix, --exit-non-zero-on-fix ]
        types_or: [ python, jupyter ]
      - id: ruff-format
        args: [ --config, pyproject.toml ]
        types_or: [ python, jupyter ]

  - repo: https://github.com/astral-sh/ty-pre-commit
    rev: v0.0.62
    hooks:
      - id: ty

  - repo: https://github.com/kynan/nbstripout
    rev: 0.9.1
    hooks:
      - id: nbstripout
        name: nbstripout
        entry: nbstripout --keep-metadata-keys="metadata.kernelspec metadata.language_info.codemirror_mode.version metadata.language_info.pygments_lexer metadata.language_info.version"
        types_or: [python, pyi, jupyter]
        language: python
